// examples/reacty/client/pages/about/__[id].tsx
import { useHead } from "@hushkey/howl-react/head";
import { useAtom } from "@hushkey/howl-react/store";
import { useHowlState } from "@hushkey/howl-react/state";
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "@howl/config";
import { countAtom } from "../../store/index.store.ts";

/**
 * AOT route (`__` prefix) — navigated to entirely on the client (no server
 * round-trip), rendered from the AOT chunk. Still SSRs on a direct landing.
 */
export default function AboutId(props: ReactPageProps<unknown, State>) {
  const [count, setCount] = useAtom(countAtom);
  const state = useHowlState<State>();

  useHead({
    title: `${props.params?.id} · About · Reacty`,
    meta: [{ name: "description", content: "About this React-on-Howl AOT demo." }],
  });

  return (
    <main className="container">
      <header>
        <h1 className="text-2xl font-bold mb-2">📖 About {props.params?.id}</h1>
        <p className="text-base-content/70">
          A second full React page, served at <code>{props.url.pathname}</code>{" "}
          by Howl's own file-system router — no React Router involved.
        </p>
      </header>
      <section className="mt-4">
        <p>Its own counter, shared with the home page via the jotai store:</p>
        <button
          type="button"
          className="btn btn-secondary btn-sm mt-2"
          onClick={() => setCount(count + 1)}
        >
          clicked {count} times
        </button>
      </section>
      <section className="mt-4">
        <p className="text-base-content/70">
          From the auto-synced <code>useHowlState()</code> mirror (server{" "}
          <code>ctx.state</code>, no prop-drilling): app title ={" "}
          <strong className="text-primary">{state.title}</strong>.
        </p>
      </section>
    </main>
  );
}

// examples/_vue/client/pages/about/__[id].vue
<template>
    <main class="container">
        <header>
            <h1>📖 About {{ props.params?.id }}</h1>
            <p>
                A second full Vue page, served at <code>{{ props.url.pathname }}</code> by Howl's own
                file-system router — no Vue Router involved.
            </p>
        </header>
        <section>
            <p>Its own counter, to prove this route hydrates independently:</p>
            <button class="cta" type="button" @click="store.inc()">
                clicked {{ store.count }} times
            </button>
        </section>
        <section>
            <p>
                From the auto-synced <code>state</code> store (mirrors server
                <code>ctx.state</code>, no prop-drilling): app title =
                <strong>{{ props.state.client?.title }}</strong>.
                <strong>{{ props.state.user }}</strong>.
            </p>
        </section>
    </main>
</template>

<script setup lang="ts">
import type { VuePageProps } from "@hushkey/howl-vue";
import type { State } from "@howl/config";
import { useStore } from "../../store/index.store.ts";
import { useHead } from "@hushkey/howl-vue/head";

const props = defineProps<VuePageProps<unknown, State>>();
const store = useStore();

useHead({
    title: `${props.params?.id} · About · Vuety`,
    meta: [{ name: "description", content: "About this Vue-on-Howl demo." }],
});
</script>

<style scoped>
.cta {
    font: inherit;
    font-weight: 600;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    border: 1px solid #6366f1;
    background: #e0e7ff;
    color: #312e81;
    cursor: pointer;
}
</style>
