// examples/_react/client/pages/about/index.tsx
import { useHead } from "@hushkey/howl-react/head";
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "@howl/config";

export default function About(props: ReactPageProps<unknown, State>) {
  useHead({
    title: "About · Reacty",
    meta: [{ name: "description", content: "About this React-on-Howl demo." }],
  });

  return (
    <main className="container">
      <header>
        <h1 className="text-2xl font-bold mb-2">📖 About</h1>
        <p className="text-base-content/70">
          A second full React page, served at <code>{props.url.pathname}</code>{" "}
          by Howl's own file-system router — no React Router involved.
        </p>
      </header>
    </main>
  );
}

// examples/_vue/client/pages/about/index.vue
<template>
  <main class="container">
    <header>
      <h1>📖 About</h1>
      <p>
        A second full Vue page, served at <code>{{ props.url.pathname }}</code> by Howl's own
        file-system router — no Vue Router involved.
      </p>
    </header>
    <section>
      <p>Its own counter, to prove this route hydrates independently:</p>
      <button class="cta" type="button" @click="store.inc()">
        clicked {{ store.count }} times
      </button>
    </section>
    <section>
      <p>
        From the auto-synced <code>state</code> store (mirrors server
        <code>ctx.state</code>, no prop-drilling): app title =
        <strong>{{ props.state.client?.title }}</strong>.
        <strong>{{ props.state.user }}</strong>.
      </p>
    </section>
    <a href="/about/12345">
      <button class="cta" type="button">TRY /:id</button>
    </a>
  </main>
</template>

<script setup lang="ts">
import { useHead } from "@hushkey/howl-vue/head";
import type { VuePageProps } from "@hushkey/howl-vue";
import type { State } from "@howl/config";
import { useStore } from "../../store/index.store.ts";

const props = defineProps<VuePageProps<unknown, State>>();
const store = useStore();

useHead({
  title: "About · Vuety",
  meta: [{ name: "description", content: "About this Vue-on-Howl demo." }],
});
</script>

<style scoped>
.cta {
  font: inherit;
  font-weight: 600;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  border: 1px solid #6366f1;
  background: #e0e7ff;
  color: #312e81;
  cursor: pointer;
}
</style>
