// examples/_vue/client/pages/about/__[id].vue
<template>
    <main class="container">
        <header>
            <h1>📖 About {{ props.params?.id }}</h1>
            <p>
                A second full Vue page, served at <code>{{ props.url.pathname }}</code> by Howl's own
                file-system router — no Vue Router involved.
            </p>
        </header>
        <section>
            <p>Its own counter, to prove this route hydrates independently:</p>
            <button class="cta" type="button" @click="store.inc()">
                clicked {{ store.count }} times
            </button>
        </section>
        <section>
            <p>
                From the auto-synced <code>state</code> store (mirrors server
                <code>ctx.state</code>, no prop-drilling): app title =
                <strong>{{ props.state.client?.title }}</strong>.
                <strong>{{ props.state.user }}</strong>.
            </p>
        </section>
    </main>
</template>

<script setup lang="ts">
import type { VuePageProps } from "@hushkey/howl-vue";
import type { State } from "@howl/config";
import { useStore } from "../../store/index.store.ts";
import { useHead } from "@hushkey/howl-vue/head";

const props = defineProps<VuePageProps<unknown, State>>();
const store = useStore();

useHead({
    title: `${props.params?.id} · About · Vuety`,
    meta: [{ name: "description", content: "About this Vue-on-Howl demo." }],
});
</script>

<style scoped>
.cta {
    font: inherit;
    font-weight: 600;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    border: 1px solid #6366f1;
    background: #e0e7ff;
    color: #312e81;
    cursor: pointer;
}
</style>

// examples/_react-shadcn/client/pages/about/__[id].tsx
import { useHead } from "@hushkey/howl-react/head";
import { useAtom } from "@hushkey/howl-react/store";
import { useHowlState } from "@hushkey/howl-react/state";
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "@howl/config";
import { countAtom } from "../../store/index.store.ts";
import { Button } from "@/components/ui/button.tsx";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card.tsx";

/**
 * AOT route (`__` prefix) — navigated to entirely on the client (no server
 * round-trip), rendered from the AOT chunk. Still SSRs on a direct landing.
 */
export default function AboutId(props: ReactPageProps<unknown, State>) {
  const [count, setCount] = useAtom(countAtom);
  const state = useHowlState<State>();

  useHead({
    title: `${props.params?.id} · About · Howl + shadcn/ui`,
    meta: [{ name: "description", content: "An AOT-navigated shadcn page on Howl." }],
  });

  return (
    <main className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>📖 About {props.params?.id}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Served at <code className="rounded bg-muted px-1 py-0.5">{props.url.pathname}</code>
            {" "}
            — this route is client-rendered on nav from its AOT chunk.
          </p>
          <div className="flex items-center gap-3">
            <span className="text-sm">Shared counter:</span>
            <Button variant="secondary" size="sm" onClick={() => setCount(count + 1)}>
              clicked {count} times
            </Button>
          </div>
          <p className="text-sm text-muted-foreground">
            From the auto-synced{" "}
            <code className="rounded bg-muted px-1 py-0.5">useHowlState()</code> mirror: app title =
            {" "}
            <strong className="text-foreground">{state.title}</strong>.
          </p>
        </CardContent>
      </Card>
    </main>
  );
}
