// examples/vuety/client/pages/_layout.vue
<template>
  <div class="layout">
    <nav class="navbar">
      <a href="/" :class="{ active: url.pathname === '/' }">Home</a>
      <a href="/about" :class="{ active: url.pathname === '/about' }">About</a>
      <a href="/about/12345" :class="{ active: route === '/about/:id' }">ID (AOT)</a>
      <a href="/ssg" :class="{ active: url.pathname === '/ssg' }">Static (SSG)</a>
      <span class="here">· routed at {{ url.pathname }}</span>
    </nav>
    <slot />
  </div>
</template>

<script setup lang="ts">
import type { VuePageProps } from "@hushkey/howl-vue";
import type { State } from "@howl/config";

const props = defineProps<VuePageProps<unknown, State>>();
</script>

<style scoped>
.layout {
  padding: 1.25rem;
  max-width: 42rem;
  margin: 0 auto;
}
.navbar {
  display: flex;
  gap: 1rem;
  align-items: center;
  margin-bottom: 1.5rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid #e2e8f0;
}
.navbar a {
  color: #475569;
  text-decoration: none;
  font-weight: 500;
}
.navbar a.active {
  color: #4f46e5;
  font-weight: 700;
}
.navbar .here {
  color: #94a3b8;
  font-size: 0.8rem;
}
</style>

// examples/_react/client/pages/_layout.tsx
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "@howl/config";

/** Shared layout — nav + active-link, like vuety's `_layout.vue`. */
export default function Layout(props: ReactPageProps<unknown, State>) {
  const Outlet = props.Component!;
  const path = props.url.pathname;
  const link = (active: boolean) =>
    active ? "font-bold text-primary" : "text-base-content/70 hover:text-base-content";
  return (
    <div className="max-w-2xl mx-auto p-5">
      <nav className="flex gap-4 items-center mb-6 pb-3 border-b border-base-300">
        <a href="/" className={link(path === "/")}>Home</a>
        <a href="/about" className={link(path === "/about")}>About</a>
        <a href="/about/12345" className={link(props.route === "/about/:id")}>ID (AOT)</a>
        <a href="/ssg" className={link(path === "/ssg")}>Static (SSG)</a>
        <span className="text-xs text-base-content/40">· routed at {path}</span>
      </nav>
      <Outlet />
    </div>
  );
}
