// examples/vuety/client/pages/_app.vue
<template>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <title> + per-page meta are managed by useHead() in each page -->
    <link rel="stylesheet" href="/style.css" /> 
    <!-- we will have look to build a client entry so I can import css 
     and bundle everything instead using the network -->
  </head>
  <body client-nav client-prefetch pinia>
    <div class="app-shell">
      <header class="bg-fuchsia-600 py-4">{{ state?.client?.title }}</header>
      <slot />
    </div>
  </body>
</template>

<script setup lang="ts">
defineProps<{ state?: { client?: { title?: string } } }>();
</script>

// examples/software-www/client/pages/_app.tsx
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "../../howl.config.ts";

const OG_IMAGE = "/og.png";

/**
 * Document shell. Owns the `<html>` + app-wide `<head>` (charset, viewport,
 * stylesheet, favicon, default share image). Per-page title and description
 * come from each page's `useHead()` (`@hushkey/howl-react/head`).
 */
export default function App(props: ReactPageProps<unknown, State>) {
  const Outlet = props.Component!;
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="stylesheet" href="/style.css" />
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />

        <meta property="og:type" content="website" />
        <meta property="og:image" content={OG_IMAGE} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content={OG_IMAGE} />
      </head>
      <body client-nav="true" client-prefetch="true">
        <Outlet />
      </body>
    </html>
  );
}
