// examples/kawaii-www/client/pages/_error.vue
<template>
  <main class="mx-auto flex min-h-[70vh] max-w-160 flex-col items-center justify-center px-(--pad) text-center">
    <div class="k-grad-text text-[clamp(72px,14vw,140px)] font-extrabold leading-none">{{ status }}</div>
    <h2 class="mt-1 text-[clamp(20px,3vw,28px)] font-bold">{{ message }}</h2>
    <p class="mt-3.5 max-w-[44ch] leading-[1.6] text-base-content/60">
      The page you're looking for could not be found. Head back to the home page to keep browsing.
    </p>
    <a href="/" class="k-cta mt-7">← kawaii<span class="opacity-70">(</span>home<span class="opacity-70">)</span></a>
  </main>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useHead } from "@hushkey/howl-vue/head";

const props = defineProps<{ error: { status?: number; message?: string } | null }>();

const errorMap: Record<number, string> = {
  400: "Bad Request",
  401: "Unauthorized",
  403: "Forbidden",
  404: "Not Found",
  500: "Internal Server Error",
};

const status = computed(() => props.error?.status ?? 500);
const message = computed(() => props.error?.message || errorMap[status.value] || "Unknown error");

useHead({ title: computed(() => `${status.value} · kawaii(x,y)`) });
</script>

// examples/hybrid-spa/client/pages/_error.tsx
import { Head } from "@hushkey/howl/runtime";
import type { JSX } from "preact/jsx-dev-runtime";

export default function Error({ error }: { error: unknown }): JSX.Element {
  const errorMap = {
    404: "Not Found",
    500: "Internal Server Error",
    403: "Forbidden",
    401: "Unauthorized",
    400: "Bad Request",
  };
  const errorMessage = errorMap[(error as { status: number }).status as keyof typeof errorMap] ||
    "Unknown error";
  const status = (error as { status: number }).status || 500;

  return (
    <>
      <Head>
        <title>Error {errorMessage}</title>
      </Head>
      {/* center */}
      <div class="pt-20 pb-40 flex justify-center px-5 bg-base-100 min-h-screen">
        <div class="text-center w-full max-w-2xl">
          <h1 class="text-6xl sm:text-6xl font-bold mb-4 text-error">{status}</h1>
          <h2 class="text-3xl sm:text-3xl font-semibold mb-2">Oops!</h2>
          <p class="text-lg sm:text-lg mb-3 text-base-content/70">{errorMessage}</p>
          <p class="text-base mb-8 text-base-content/60 leading-relaxed">
            The page you're looking for could not be found. We appreciate if you could go back to
            the home page to continue browsing.
          </p>
          <a
            href="/"
            class="btn btn-primary btn-md rounded-lg mt-4"
            client-nav
          >
            Go Back Home
          </a>
        </div>
      </div>
    </>
  );
}
