// examples/nobiru-www/client/pages/_app.tsx
import type { ReactPageProps } from "@hushkey/howl-react";
import type { State } from "@howl/config";

/**
 * Document shell. Owns the `<html>` and the app-wide `<head>`; per-page title,
 * description and OG tags come from each page's `useHead()`. No webfont — the
 * system stack Tailwind ships with is the type.
 */
export default function App(props: ReactPageProps<unknown, State>) {
  const Outlet = props.Component!;
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="stylesheet" href="/style.css" />
        <link rel="icon" type="image/png" href="/logo-192.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body client-nav="true" client-prefetch="true" className="min-h-screen antialiased">
        <Outlet />
      </body>
    </html>
  );
}

// examples/_vue/client/pages/_app.vue
<template>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- <title> + per-page meta are managed by useHead() in each page -->
    <link rel="stylesheet" href="/style.css" /> 
    <!-- we will have look to build a client entry so I can import css 
     and bundle everything instead using the network -->
  </head>
  <body client-nav client-prefetch pinia>
    <div class="app-shell">
      <header class="bg-fuchsia-600 py-4 font-bold pl-10">{{ props.state?.client?.title }}</header>
      <slot />
    </div>
  </body>
</template>

<script setup lang="ts">
import type { VuePageProps } from "@hushkey/howl-vue";
import type { State } from "@howl/config";

const props = defineProps<VuePageProps<unknown, State>>();
</script>
